name: experimental-desktop
description: This is my personal OS image.

base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: latest

modules:
  - type: dnf
    source: ghcr.io/blue-build/modules@sha256:50747361c625c0a5afac314f174243ca7d14373dbbdd20e2261c1f9384a632de
    install:
      install-weak-deps: false
      packages:
        - adw-gtk3-theme
        - gnome-disk-utility
        - papirus-icon-theme
        - qt6ct
    remove:
      packages:
        - javascriptcoregtk4.1
        - webkit2gtk4.1
        - xmlsec1-openssl
        - xmlsec1
        - open-vm-tools
        - open-vm-tools-desktop
        - thermald
        - stoken-libs
        - libpskc
        - openconnect
        - libreswan
        - libreswan-minimal
        - sstp-client
        - vpnc
        - vpnc-script
        - qcom-wwan-firmware
        - golang-github-katalix-l2tp
        - NetworkManager-bluetooth
        - NetworkManager-l2tp
        - NetworkManager-l2tp-gnome
        - NetworkManager-openconnect
        - NetworkManager-openconnect-gnome
        - NetworkManager-libreswan
        - NetworkManager-libreswan-gnome
        - NetworkManager-sstp
        - NetworkManager-sstp-gnome
        - NetworkManager-vpnc
        - NetworkManager-vpnc-gnome
        - NetworkManager-wwan
        - sane-backends-libs
        - sane-backends-drivers-scanners
        - fwupd-plugin-modem-manager
        - sane-backends-drivers-cameras
        - sane-backends
        - libsane-hpaio
        - hplip-libs
        - hplip
        - ModemManager
        - cups
        - cups-browsed
        - cups-client
        - cups-ipptool
        - python3-cups
        - libcupsfilters
        - cups-filters
        - bluez-cups
        - dymo-cups-drivers
        - gutenprint-cups
        - gutenprint
        - gutenprint-libs
        - cups-filters-driverless
        - fprintd
        - libfprint
        - system-config-printer-libs
        - ghostscript-tools-printing
        - braille-printer-app
        - printer-driver-brlaser
        - system-config-printer
        - system-config-printer-udev
        - fprintd-pam
        - bluez
        - bluez-obexd
        - blueman
        - ptouch-driver
        - libppd
        - splix
        - ghostscript
        - ghostscript-tools-fontutils
        - c2esp
        - xdg-desktop-portal-wlr
        - virtualbox-guest-additions
        - sssd-client
        - sssd-common
        - sssd-kcm
        - sssd-krb5-common
        - sssd-nfs-idmap
        - steam-devices
        - spice-vdagent
        - spice-webdavd
        - samba-client
        - sane-airscan
        # - ppp
        # - ntfs-3g
        # - ntfs-3g-libs
        # - ntfs-3g-system-compression
        # - ntfsprogs
        # - ibus
        # - ibus-anthy
        # - ibus-anthy-python
        # - ibus-chewing
        # - ibus-gtk3
        # - ibus-gtk4
        # - ibus-hangul
        # - ibus-libpinyin
        # - ibus-libs
        # - ibus-m17n
        # - ibus-panel
        # - ibus-setup
        # - ibus-typing-booster
        # - ibus-xinit
        # - hyperv-daemons
        # - hyperv-daemons-license
        # - hypervfcopyd
        # - mozilla-filesystem
        # - nfs-utils
        # - nilfs-utils
        # - cifs-utils
        # - lvm2
        # - lvm2-libs
        # - mcelog
        # - low-memory-monitor
        # - hypervkvpd
        # - hypervvssd
        # - hplip-common
        # - hunspell
        # - hunspell-en
        # - hunspell-en-GB
        # - hunspell-en-US
        # - hunspell-filesystem
        # - gvfs-smb
        # - gssproxy
        # - dbus-x11
        # - enchant2
        # - cifs-utils-info
        # - python3-enchant
        # - openssh-server

  - type: script
    source: ghcr.io/blue-build/modules@sha256:b143423fb9560a24f362db36621c7e81da56551d32fbbc97e267e811dd7f0c27
    scripts:
      - setqt6ct.sh
      - dnfautoremove.sh